x-app: &app
  image: wake-up-device-app
  build:
    context: .
  environment:
    DB_STORAGE: /data/wake-up-device.sqlite
    WOL_BROADCAST_ADDRESS: ${WOL_BROADCAST_ADDRESS:-255.255.255.255}
  volumes:
    - sqlite-data:/data

services:
  app:
    <<: *app
    network_mode: host
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  migrate:
    <<: *app
    command: npm run db:migrate

volumes:
  sqlite-data:
