CREATE TABLE IF NOT EXISTS devices (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL,
    type VARCHAR(20) NULL,
    mac_address VARCHAR(20) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
);
